version: "3.1"

services:
    db:
     image: postgres:latest
     ports:
      - 5432:5432

    dbviewer:
     image: dpage/pgadmin4:latest
     ports:
      - 8080:8080
     depends_on:
      - db

